[package]
name = "ffi-playground"
version = "0.1.0"
authors = ["depressionlab"]
description = "Experimentations with FFI."
edition = "2024"
license = "EUPL-1.2"
readme = "README.md"
repository = "https://github.com/depressionlab/ffi-playground"
homepage = "https://github.com/depressionlab/ffi-playground"

[dependencies]
core-foundation = "0.10.1"
libc = { version = "0.2.190" }
libloading = { version = "0.9.0" }
clap = { version = "4.6.7", features = ["derive", "wrap_help"] }
clap_complete = { version = "4.6.11" }
ratatui = { version = "0.30.2" }
eyre = { version = "0.6.14" }
color-eyre = { version = "0.6.5" }
owo-colors = { version = "4.4.0" }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[profile.dev.package."*"]
opt-level = 3
